// 中文翻译映射 —— 肌群 / 器械 / 训练类型 / 动作名称
//
// ⚠️ 本文件当前**没有任何引用**（已核实：src/ 无 import，构建产物里也搜不到它的译名）。
// 它是早期用 @bryllim/workout-guide 那套数据时的翻译层 —— key 是 'bench-press'
// 这类通用 slug；后来数据源换成 Devillmy/exercises-dataset-zh（数字 slug，
// 且 catalog.json 自带 nameZh / bodyPartZh 等字段），这个文件就被架空了。
// 保留原因：暂无。**如果要清理，删掉即可**（先确认没人打算复用）。

const muscleZh: Record<string, string> = {
  Adductors: '内收肌',
  Back: '背部',
  Biceps: '肱二头肌',
  Calves: '小腿',
  Cardio: '心肺',
  Chest: '胸部',
  Core: '核心',
  Forearms: '前臂',
  Glutes: '臀部',
  Grip: '握力',
  Groin: '腹股沟',
  Hamstrings: '腘绳肌',
  Hips: '髋部',
  Lats: '背阔肌',
  Legs: '腿部',
  'Lower Back': '下背',
  Mobility: '活动度',
  'Posterior Chain': '后链',
  Quads: '股四头肌',
  'Rear Delts': '后三角肌',
  Shoulders: '肩部',
  Triceps: '肱三头肌',
  'Upper Back': '上背',
};

const equipmentZh: Record<string, string> = {
  Barbell: '杠铃',
  Bench: '卧推凳',
  Bodyweight: '自重',
  Box: '跳箱',
  Cable: '绳索',
  Cardio: '有氧器械',
  Chair: '椅子',
  Doorway: '门框',
  Dumbbell: '哑铃',
  Kettlebell: '壶铃',
  Machine: '固定器械',
  Plate: '杠铃片',
  'Pull-up Bar': '单杠',
  'Resistance Band': '弹力带',
  'Stability Ball': '瑜伽球',
  Towel: '毛巾',
  Wall: '墙壁',
};

const typeZh: Record<string, string> = {
  weight_reps: '负重次数',
  bodyweight_reps: '自重次数',
  duration: '计时',
  distance_duration: '距离/计时',
  assisted_bodyweight: '辅助自重',
};

// 动作名映射。键为 slug，与 manifest 中的 slug 一致。
const exerciseZh: Record<string, string> = {
  // 胸部
  'bench-press': '杠铃卧推',
  'incline-bench-press': '上斜杠铃卧推',
  'incline-dumbbell-press': '上斜哑铃卧推',
  'dumbbell-bench-press': '哑铃卧推',
  'decline-bench-press': '下斜杠铃卧推',
  'machine-chest-press': '器械推胸',
  'pec-deck': '蝴蝶机夹胸',
  'cable-fly': '绳索夹胸',
  'push-up': '俯卧撑',
  'weighted-push-up': '负重俯卧撑',
  'dumbbell-fly': '哑铃飞鸟',
  'incline-cable-fly': '上斜绳索夹胸',
  'decline-dumbbell-press': '下斜哑铃卧推',
  'smith-machine-bench-press': '史密斯卧推',
  'chest-dip': '胸部双杠臂屈伸',
  'incline-push-up': '上斜俯卧撑',
  'knee-push-up': '跪姿俯卧撑',
  'wide-push-up': '宽距俯卧撑',
  'decline-push-up': '下斜俯卧撑',
  'archer-push-up': '弓箭手俯卧撑',
  'typewriter-push-up': '打字机俯卧撑',
  'explosive-push-up': '爆发俯卧撑',
  'hindu-push-up': '印度俯卧撑',
  'wall-push-up': '墙壁俯卧撑',
  'seal-jack': '海豹开合跳',
  'doorway-chest-stretch': '门框胸部拉伸',

  // 肩部
  'overhead-press': '杠铃推举',
  'seated-dumbbell-press': '坐姿哑铃推举',
  'arnold-press': '阿诺德推举',
  'lateral-raise': '哑铃侧平举',
  'cable-lateral-raise': '绳索侧平举',
  'front-raise': '哑铃前平举',
  'upright-row': '直立划船',
  'landmine-press': '地雷管推举',
  'machine-shoulder-press': '器械肩推',
  'standing-dumbbell-press': '站姿哑铃推举',
  'push-press': '借力推举',
  'machine-lateral-raise': '器械侧平举',
  'cable-front-raise': '绳索前平举',
  'plate-front-raise': '杠铃片前平举',
  'pike-push-up': '派克俯卧撑',
  'feet-elevated-pike-push-up': '抬脚派克俯卧撑',
  'wall-walk': '靠墙倒立走',
  'wall-handstand-push-up': '靠墙倒立撑',
  'handstand-push-up': '倒立撑',
  'battle-ropes': '战绳',
  'arm-circles': '手臂绕环',
  'cross-body-shoulder-stretch': '体前肩部拉伸',

  // 后三角肌
  'rear-delt-fly': '俯身反式飞鸟',
  'reverse-pec-deck': '反向蝴蝶机',
  'bent-over-rear-delt-raise': '俯身侧平举',
  'cable-rear-delt-fly': '绳索反式飞鸟',

  // 背部 / 上背
  'face-pull': '面拉',
  'barbell-row': '杠铃划船',
  't-bar-row': 'T 杠划船',
  'dumbbell-bent-over-row': '哑铃俯身划船',
  'one-arm-dumbbell-row': '单臂哑铃划船',
  'chest-supported-row': '胸靠划船',
  'seated-row': '坐姿绳索划船',
  'machine-row': '器械划船',
  'shrug': '杠铃耸肩',
  'pendlay-row': '潘德雷划船',
  'inverted-row': '反向划船',
  'meadows-row': '梅多斯划船',
  'single-arm-cable-row': '单臂绳索划船',
  'rack-pull': '架上硬拉',
  'dumbbell-shrug': '哑铃耸肩',
  'doorway-row': '门框划船',
  'towel-row': '毛巾划船',
  'prone-y-raise': '俯卧 Y 字举',
  'prone-t-raise': '俯卧 T 字举',
  'reverse-snow-angel': '反向雪天使',
  'scapular-push-up': '肩胛俯卧撑',
  'band-pull-apart': '弹力带拉开',
  'banded-face-pull': '弹力带面拉',
  'banded-row': '弹力带划船',
  'rowing': '划船机',
  'swimming': '游泳',
  'skierg': '滑雪机',
  'childs-pose': '婴儿式',

  // 背阔肌
  'lat-pulldown': '高位下拉',
  'close-grip-lat-pulldown': '窄距高位下拉',
  'straight-arm-pulldown': '直臂下压',
  'pull-up': '引体向上',
  'assisted-pull-up': '辅助引体向上',
  'weighted-pull-up': '负重引体向上',
  'wide-grip-lat-pulldown': '宽距高位下拉',
  'neutral-grip-pull-up': '对握引体向上',
  'active-hang': '主动悬垂',
  'scapular-pull-up': '肩胛引体',
  'negative-pull-up': '离心引体向上',
  'commando-pull-up': '突击队引体',
  'l-sit-pull-up': 'L 支撑引体',
  'towel-pull-up': '毛巾引体',
  'banded-lat-pulldown': '弹力带下拉',

  // 下背 / 后链
  'deadlift': '硬拉',
  'sumo-deadlift': '相扑硬拉',
  'trap-bar-deadlift': '六角杠硬拉',
  'back-extension': '山羊挺身',
  'superman': '超人式',
  'superman-hold': '超人式保持',

  // 肱二头肌
  'chin-up': '反手引体向上',
  'assisted-chin-up': '辅助反手引体',
  'weighted-chin-up': '负重反手引体',
  'bicep-curl': '哑铃弯举',
  'hammer-curl': '锤式弯举',
  'preacher-curl': '牧师凳弯举',
  'cable-curl': '绳索弯举',
  'incline-dumbbell-curl': '上斜哑铃弯举',
  'concentration-curl': '集中弯举',
  'ez-bar-curl': '曲杆弯举',
  'spider-curl': '蜘蛛弯举',
  'rope-hammer-curl': '绳索锤式弯举',
  'drag-curl': '拖拽弯举',

  // 肱三头肌
  'tricep-pushdown': '绳索下压',
  'overhead-tricep-extension': '过顶臂屈伸',
  'skull-crusher': '仰卧臂屈伸',
  'close-grip-bench-press': '窄距卧推',
  'dip': '双杠臂屈伸',
  'assisted-dip': '辅助双杠臂屈伸',
  'weighted-dip': '负重双杠臂屈伸',
  'rope-tricep-pushdown': '绳索下压（绳把）',
  'dumbbell-skull-crusher': '哑铃仰卧臂屈伸',
  'single-dumbbell-skullcrusher': '单哑铃仰卧臂屈伸',
  'dumbbell-overhead-tricep-extension': '哑铃过顶臂屈伸',
  'single-arm-dumbbell-tricep-extension': '单臂哑铃臂屈伸',
  'bench-dip': '凳上臂屈伸',
  'tricep-kickback': '俯身臂屈伸',
  'diamond-push-up': '钻石俯卧撑',
  'chair-dip': '椅子臂屈伸',
  'crab-walk': '螃蟹走',

  // 前臂 / 握力
  'reverse-curl': '反握弯举',
  'wrist-curl': '腕弯举',
  'wrist-extension': '腕伸展',
  'farmer-carry': '农夫行走',
  'dead-hang': '死挂',

  // 股四头肌
  'squat': '杠铃深蹲',
  'front-squat': '前蹲',
  'hack-squat': '哈克深蹲',
  'leg-press': '腿举',
  'bulgarian-split-squat': '保加利亚分腿蹲',
  'walking-lunge': '行走弓步',
  'step-up': '登台阶',
  'leg-extension': '腿屈伸',
  'goblet-squat': '高脚杯深蹲',
  'smith-machine-squat': '史密斯深蹲',
  'belt-squat': '腰带深蹲',
  'reverse-lunge': '后撤弓步',
  'split-squat': '分腿蹲',
  'smith-machine-bulgarian-split-squat': '史密斯保加利亚分腿蹲',
  'smith-machine-reverse-lunge': '史密斯后撤弓步',
  'smith-machine-split-squat': '史密斯分腿蹲',
  'heel-elevated-goblet-squat': '垫脚高脚杯深蹲',
  'front-foot-elevated-split-squat': '前脚抬高分腿蹲',
  'dumbbell-lateral-lunge': '哑铃侧向弓步',
  'landmine-squat': '地雷管深蹲',
  'wall-sit': '靠墙静蹲',
  'jump-squat': '深蹲跳',
  'bodyweight-squat': '自重深蹲',
  'pistol-squat': '单腿深蹲',
  'assisted-pistol-squat': '辅助单腿深蹲',
  'shrimp-squat': '虾式深蹲',
  'cossack-squat': '哥萨克深蹲',
  'sissy-squat': '西斯深蹲',
  'forward-lunge': '前弓步',
  'lateral-lunge': '侧向弓步',
  'skater-squat': '滑冰式深蹲',
  'single-leg-box-squat': '单腿箱蹲',
  'step-down': '单腿下台阶',
  'banded-squat': '弹力带深蹲',
  'standing-quad-stretch': '站姿股四头肌拉伸',

  // 腘绳肌
  'romanian-deadlift': '罗马尼亚硬拉',
  'leg-curl': '俯卧腿弯举',
  'seated-leg-curl': '坐姿腿弯举',
  'good-morning': '早安式',
  'lying-leg-curl': '俯卧腿弯举（器械）',
  'nordic-hamstring-curl': '北欧腿弯举',
  'single-leg-romanian-deadlift': '单腿罗马尼亚硬拉',
  'smith-machine-romanian-deadlift': '史密斯罗马尼亚硬拉',
  'dumbbell-romanian-deadlift': '哑铃罗马尼亚硬拉',
  'kettlebell-romanian-deadlift': '壶铃罗马尼亚硬拉',
  'landmine-romanian-deadlift': '地雷管罗马尼亚硬拉',
  'lying-hamstring-walkout': '俯卧腘绳肌走',
  'towel-hamstring-curl': '毛巾腿弯举',
  'stability-ball-hamstring-curl': '瑜伽球腿弯举',
  'hamstring-stretch': '腘绳肌拉伸',
  'seated-forward-fold-stretch': '坐姿体前屈',

  // 臀部
  'hip-thrust': '臀推',
  'glute-bridge': '臀桥',
  'cable-kickback': '绳索后踢腿',
  'hip-abduction-machine': '髋外展器械',
  'single-leg-glute-bridge': '单腿臀桥',
  'barbell-glute-bridge': '杠铃臀桥',
  'dumbbell-glute-bridge': '哑铃臀桥',
  'dumbbell-hip-thrust': '哑铃臀推',
  'smith-machine-hip-thrust': '史密斯臀推',
  'cable-pull-through': '绳索穿越',
  'machine-glute-kickback': '器械后踢腿',
  'cable-standing-hip-abduction': '站姿绳索髋外展',
  'dumbbell-sumo-squat': '哑铃相扑深蹲',
  'dumbbell-sumo-deadlift': '哑铃相扑硬拉',
  'deficit-reverse-lunge': '垫高后撤弓步',
  'dumbbell-curtsy-lunge': '哑铃交叉弓步',
  'kettlebell-swing': '壶铃摆动',
  'glute-focused-back-extension': '臀部发力山羊挺身',
  'reverse-hyperextension': '反向山羊挺身',
  'curtsy-lunge': '交叉弓步',
  'glute-bridge-march': '臀桥交替抬腿',
  'frog-pump': '蛙式臀桥',
  'donkey-kick': '跪姿后踢腿',
  'fire-hydrant': '消防栓式抬腿',
  'clamshell': '蚌式开合',
  'hip-airplane': '髋关节飞机式',
  'side-lying-hip-abduction': '侧卧髋外展',
  'side-lying-leg-raise': '侧卧抬腿',
  'banded-glute-bridge': '弹力带臀桥',
  'banded-hip-thrust': '弹力带臀推',
  'banded-frog-pump': '弹力带蛙式臀桥',
  'banded-clamshell': '弹力带蚌式开合',
  'banded-lateral-walk': '弹力带侧向走',
  'banded-monster-walk': '弹力带怪兽走',
  'banded-donkey-kick': '弹力带后踢腿',
  'banded-fire-hydrant': '弹力带消防栓式',
  'banded-kickback': '弹力带站姿后踢腿',
  'banded-standing-hip-abduction': '弹力带站姿髋外展',
  'banded-seated-hip-abduction': '弹力带坐姿髋外展',

  // 内收肌 / 髋部
  'cable-standing-hip-adduction': '站姿绳索髋内收',
  'hip-adduction-machine': '髋内收器械',
  'kneeling-hip-flexor-stretch': '跪姿髋屈肌拉伸',
  'butterfly-stretch': '蝴蝶式拉伸',

  // 小腿
  'standing-calf-raise': '站姿提踵',
  'seated-calf-raise': '坐姿提踵',
  'donkey-calf-raise': '驴式提踵',
  'leg-press-calf-raise': '腿举提踵',
  'calf-raise': '提踵',
  'single-leg-calf-raise': '单腿提踵',
  'fast-feet': '快速碎步',
  'jump-rope': '跳绳',
  'wall-calf-stretch': '靠墙小腿拉伸',

  // 核心
  'plank': '平板支撑',
  'side-plank': '侧平板支撑',
  'hanging-leg-raise': '悬垂举腿',
  'cable-crunch': '绳索卷腹',
  'ab-wheel': '健腹轮',
  'crunch': '卷腹',
  'reverse-crunch': '反向卷腹',
  'russian-twist': '俄罗斯转体',
  'bicycle-crunch': '自行车卷腹',
  'mountain-climber': '登山跑',
  'dead-bug': '死虫式',
  'bird-dog': '鸟狗式',
  'pallof-press': '帕洛夫推',
  'cable-woodchop': '绳索伐木',
  'half-kneeling-pallof-press': '半跪帕洛夫推',
  'cable-pallof-hold': '绳索帕洛夫保持',
  'hanging-knee-raise': '悬垂举膝',
  'captains-chair-knee-raise': '船长椅举膝',
  'decline-sit-up': '下斜仰卧起坐',
  'weighted-crunch': '负重卷腹',
  'weighted-russian-twist': '负重俄罗斯转体',
  'dumbbell-side-bend': '哑铃体侧屈',
  'push-up-shoulder-tap': '俯卧撑交替摸肩',
  'hollow-body-hold': '仰卧两头起保持',
  'hollow-rock': '仰卧两头起摇摆',
  'v-up': 'V 字两头起',
  'flutter-kick': '交替打腿',
  'lying-leg-raise': '仰卧举腿',
  'toe-touch': '仰卧摸脚',
  'heel-tap': '交替触跟',
  'plank-shoulder-tap': '平板交替摸肩',
  'plank-jack': '平板开合跳',
  'bear-plank': '熊式平板',
  'bear-crawl': '熊爬',
  'inchworm': '毛毛虫爬',
  'l-sit-hold': 'L 支撑保持',
  'seated-knee-tuck': '坐姿收膝',
  'side-plank-hip-dip': '侧平板髋部下沉',
  'copenhagen-plank': '哥本哈根平板',
  'dragon-flag': '龙旗',
  'half-burpee': '半波比跳',
  'squat-thrust': '深蹲挺身',
  'banded-pallof-press': '弹力带帕洛夫推',
  'banded-woodchop': '弹力带伐木',
  'banded-dead-bug': '弹力带死虫式',

  // 有氧 / 腿部
  'running': '跑步',
  'walking': '快走',
  'cycling': '骑行',
  'stair-climber': '爬楼机',
  'elliptical': '椭圆机',
  'assault-bike': '风阻单车',
  'hiking': '徒步',
  'treadmill-incline-walk': '跑步机爬坡走',
  'burpee': '波比跳',
  'high-knees': '高抬腿',
  'jumping-jack': '开合跳',
  'skater-hop': '滑冰跳',
  'lateral-shuffle': '侧向滑步',
  'sprawl': '俯卧撑起身',

  // 活动度 / 拉伸
  'cat-cow-stretch': '猫牛式',
  'worlds-greatest-stretch': '全身拉伸',
  'leg-swings-stretch': '摆腿',
  'torso-twist-stretch': '躯干转体',
};

/** 肌群：英文 → 中文 */
export function muscleName(en: string): string {
  return muscleZh[en] ?? en;
}

/** 器械：英文 → 中文 */
export function equipmentName(en: string): string {
  return equipmentZh[en] ?? en;
}

/** 训练类型：英文 → 中文 */
export function exerciseTypeName(en: string): string {
  return typeZh[en] ?? en;
}

/** 动作名：按 slug 查中文，查不到回退英文原名 */
export function exerciseName(slug: string, fallback: string): string {
  return exerciseZh[slug] ?? fallback;
}

/** 已收录中文的动作数量，用于自检 */
export const exerciseZhCount = Object.keys(exerciseZh).length;
